  name: PluginFirst
  main: PluginFirst
  version: 1.0

  commands:
    sayhello:
      description: Says hello. Greetes Player
      usage: /sayhello

    hello:
      description: says HELLOOO
      usage: /hello

    PlayerInfo:
      description: prints several Infomations about the Player
      usage: /PlayerInfo

    setZahl:
      description: set Zahl in config file
      usage: /setZahl <number>