  name: PluginFirst
  main: PluginFirst
  version: 1.5

  commands:
    sayhello:
      description: Says hello. Greetes Player
      usage: /sayhello

    hello:
      description: says HELLOOO
      usage: /hello

    PlayerInfo:
      description: prints several Infomations about the Player
      usage: /PlayerInfo

    setZahl:
      description: set Zahl in config file
      usage: /setZahl <number>

    argsChecker:
      description: prints out arguments and their datatypes
      usage: /argsChecker <args>

    testSet:
      description: test for schedular
      usage: /testSet <true or false>
