  name: PluginFirst
  main: PluginFirst
  version: 1.0

  commands:
    sayhello:
      description: Says hello. Greetes Player
      usage: /sayhello

    hello:
      description: says HELLOOO
      usage: /hello
